### ISSUE TITLE
Can i use it on Ubuntu/Pop_Os?

### ISSUE THREAD

**Issue by arejula27** [Barbaross93/Genome#1]

**Comment by Barbarossa93** [comment]
Technically yes, but I'd imagine it'll be a lot of work. I don't use ubuntu or Pop_Os, but I'm led to believe that packages are generally outdated. I'm currently using the latest qtile-git, so that at the very least you'll have to set up yourself. Hopefully someone else who know these distros better than I do can let you know if these dots will work for you
